use std::path::PathBuf;

/// Commands the webview may call. Must match `generate_handler!` in
/// src/lib.rs and the `allow-*` permissions in capabilities/default.json
/// (checked by scripts/docs/generate.mjs).
const COMMANDS: &[&str] = &[
    "gmail_status",
    "gmail_connect",
    "gmail_cancel_connect",
    "gmail_disconnect",
    "gmail_create_draft",
    "gmail_set_custom_client",
    "gmail_clear_custom_client",
    "check_for_updates",
    "install_update",
    "export_backup",
    "import_backup",
    "create_auto_backup",
    "list_backups",
    "read_backup",
    "open_backups_folder",
    "get_preferences",
    "set_low_memory_mode",
    "restart_app",
];

fn main() {
    embed_google_client();
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}

/// Makes the owner's Google OAuth "Desktop app" client available to the code
/// as `BUILT_IN_ID` / `BUILT_IN_SECRET` in `$OUT_DIR/google_client.rs`
/// (included by src/google/client.rs). Source, in order: the
/// SI_GOOGLE_CLIENT_ID / SI_GOOGLE_CLIENT_SECRET environment variables (set by
/// the release script), or the client file in the owner's secrets folder.
/// Never from the repo. Without either, the build works but Gmail shows "not
/// set up".
///
/// The values are never printed: Cargo shows a build script's output when
/// the build fails (and always with `-vv`), so `cargo:rustc-env` would put
/// the secret on screen. Nothing read from the file ends up in a message.
fn embed_google_client() {
    for var in [
        "SI_GOOGLE_CLIENT_ID",
        "SI_GOOGLE_CLIENT_SECRET",
        "SI_SECRETS_DIR",
        "USERPROFILE",
    ] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    let (id, secret) = google_client();
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"));
    let code = format!(
        "/// The built-in Google OAuth client (generated by build.rs).\n\
         const BUILT_IN_ID: Option<&str> = {};\n\
         /// See `BUILT_IN_ID`.\n\
         const BUILT_IN_SECRET: Option<&str> = {};\n",
        rust_literal(id.as_deref()),
        rust_literal(secret.as_deref()),
    );
    // The error never includes the contents, only the reason.
    if let Err(e) = std::fs::write(out_dir.join("google_client.rs"), code) {
        panic!("couldn't write google_client.rs: {}", e.kind());
    }
}

/// The client ID and secret from the environment, else from the secrets
/// folder's client file (Google's download format).
fn google_client() -> (Option<String>, Option<String>) {
    let env = |var| std::env::var(var).ok().filter(|v| !v.is_empty());
    if let Some(id) = env("SI_GOOGLE_CLIENT_ID") {
        return (Some(id), env("SI_GOOGLE_CLIENT_SECRET"));
    }
    let dir = std::env::var_os("SI_SECRETS_DIR")
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("USERPROFILE")
                .map(|home| PathBuf::from(home).join(".secrets").join("student-invoice"))
        });
    let Some(file) = dir.map(|d| d.join("google-oauth-client.json")) else {
        return (None, None);
    };
    println!("cargo:rerun-if-changed={}", file.display());
    let Ok(text) = std::fs::read_to_string(&file) else {
        return (None, None);
    };
    let Ok(json) = serde_json::from_str::<serde_json::Value>(&text) else {
        println!(
            "cargo:warning=google-oauth-client.json is not valid JSON; building without Gmail"
        );
        return (None, None);
    };
    let creds = json.get("installed").unwrap_or(&json);
    let field = |name: &str| creds.get(name).and_then(|v| v.as_str()).map(str::to_owned);
    match (field("client_id"), field("client_secret")) {
        (Some(id), Some(secret)) => (Some(id), Some(secret)),
        _ => (None, None),
    }
}

/// `Some("...")` or `None` as Rust source. `{:?}` escapes quotes,
/// backslashes and control characters, so any value is a valid literal.
fn rust_literal(value: Option<&str>) -> String {
    match value {
        Some(v) => format!("Some({v:?})"),
        None => "None".to_owned(),
    }
}
